# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Mod Properties
mod_id = servertweaks
mod_name = Millie's Server Additions
mod_version = 1.3.0.1
mod_description = Fully configurable random additions to Fabric servers (QoL, Fun and Moderation)
mod_license = MIT
mod_authors = JustMili

archives_base_name = MilliesServerAdditions

minecraft_version_constraint = 26.2

# Dependencies
corelibs = 0.0.2a+mc26.2-Fabric
mod_menu = 20.0.1
lithium = mc26.2-0.25.3-fabric